run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - tmp

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocyclo
    - goconst
    - unconvert
    - unparam
    - prealloc
    - exportloopref
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: false
      - name: var-naming
        disabled: false

  gosec:
    excludes:
      - G104

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - goconst

  max-issues-per-linter: 0
  max-same-issues: 0
